# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a77cb08889dc46d3aad72c54c5d4157b51b300ef08d6fcb8c0895fd82f4b1edc0f80d951e98d270bcc477b344bcd9db27e5fd2c6393a4bfc519b142018df960

test:
  secret_key_base: e0a8aa45c3d722d28e087d8dd7ecd45763ceb8c9b6083576f7e4b705c210c27dec8f81e69b51e1c042e3627eda2846a4f37e0c013260f9c63754f279fe561986

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
